version: "3.9"
name: web-authentication-demo

services:

  client:
    container_name: client
    hostname: client
    build:
        context: src/
        dockerfile: Client/Dockerfile
    ports:
      - 5136:8080
    depends_on:
      - api

  api:
    container_name: api
    hostname: api
    restart: on-failure
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
      MSSQL_CONNECTION_STRING: Server=mssql,1433;Database=hubviwe-webauthn;User Id=SA;Password=Example123;TrustServerCertificate=True;
    ports:
      - 5291:8080
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    hostname: mssql
    container_name: thebase-mssql
    restart: on-failure
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Example123