version: "3.9"
name: web-authentication-demo

services:

  client:
    image: hubviwe/web-authentication-demo.client:0.0.8
    container_name: client
    hostname: client
    build:
        context: src/
        dockerfile: Client/Dockerfile
    ports:
      - 5136:8080
    depends_on:
      - api

  api:
    image: hubviwe/web-authentication-demo.api:0.0.5
    container_name: api
    hostname: api
    restart: on-failure
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Docker"
    ports:
      - 5291:8080
    depends_on:
      - mssql
      - redis-cache

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    hostname: mssql
    container_name: thebase-mssql
    restart: on-failure
    ports:
      - 1433:1433
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Example123"
    volumes:
      - sqlsystem:/var/opt/mssql/

  redis-cache:
    image: redis:latest
    hostname: redis
    restart: always
    container_name: redis-cache
    ports:
      - 6379:6379

volumes:
  sqlsystem:
